### ISSUE TITLE
PRESENTATION CHECKLIST

### ISSUE THREAD

**Issue by ImpunityJainne** [wheresdylan/project_2#15]
- [ ] 10 minutes
- [ ] describe app concept overall
- [ ] describe motivation for development
- [ ] describe design process
- [ ] talk about technologies used and how they work
- [ ] demonstration of app functionality
- [ ] directions for future development
